WebOfferAdmin/src/main/java/com/crmweb/jsfbean/UserPasswordBean.java
package com.crmweb.jsfbean;

import com.crmweb.services.ReportingService;
import com.crmweb.services.ServiceLogin;
import com.shared.transfers.SearchUser;
import com.shared.transfers.UserLevel;
import com.shared.transfers.WebUserData;
import org.apache.commons.io.FilenameUtils;
import org.primefaces.component.datatable.DataTable;
import org.primefaces.model.file.UploadedFileWrapper;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.Part;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;

@ManagedBean
@ViewScoped
public class UserPasswordBean extends BaseJsfBean {
    private static final long serialVersionUID = 6754119563563228374L;

    private transient ServiceLogin serviceLogin;

    private transient ReportingService reportingService;

    private WebUserData alterUser = new WebUserData();

    private String oldpassword;

    private String newPasswordA;

    private String newPasswordB;

    private SearchUser searchUser = new SearchUser();

    private List<WebUserData> otherUsers;

    private WebUserData currentUser;

    private Part signature;


    private transient UploadedFileWrapper newSignature;

    private List<UserLevel> accessLevels = new ArrayList<>();

    private DataTable userTable;
    private WebUserData newUser;

    @Override
    protected void initialize()  {
        for (UserLevel aUserLevel : UserLevel.values()) {
            accessLevels.add(aUserLevel);
        }

        try {
            alterUser = (WebUserData) getWebUserData().clone();
        } catch (CloneNotSupportedException e) {
        }
        this.setActiveMenuDef("Instellingen");
        this.setViewTitle("Uw instellingen");
    }

    public void haalGebruikersOp(){
        otherUsers = serviceLogin.haalGebruikersOp(searchUser, this.getWebUserData().getUserid());
        if (otherUsers == null || otherUsers.size() == 0) {
            FacesContext facesContext = FacesContext.getCurrentInstance();
            FacesMessage facesMessage = new FacesMessage( "Er zijn geen gebruikers gevonden.");
            facesContext.addMessage("ZoekGebruiker:voornaam", facesMessage);
            otherUsers = null;
        }
    }

    public void cancelListShow(){
        otherUsers = null;
    }

    public void annuleerEdit(){
        this.currentUser = null;
    }


    public String editUser(){
        currentUser = (WebUserData) getUserTable().getRowData();

        return null;
    }

    public void addNewUser(){
        newUser = new WebUserData();
        newUser.setCurrentlevel(UserLevel.GEEN);
    }

    public void saveNewUser(){
        boolean userIdAvailable = serviceLogin.isUserIdFree(newUser);
        if (!userIdAvailable) {

            FacesContext facesContext = FacesContext.getCurrentInstance();
            FacesMessage facesMessage = new FacesMessage( "User ID `"+ newUser.getUserid() +
                    "` is al bezet.");
            facesContext.addMessage("GebruikerToevoegen:userID", facesMessage);
            return;
        }

        if (newUser.getUserid().trim().length() < 6){
            FacesContext facesContext = FacesContext.getCurrentInstance();
            FacesMessage facesMessage = new FacesMessage( "User ID  moet minimaal 6 karakters lang zijn.");
            facesContext.addMessage("GebruikerToevoegen:userID", facesMessage);
            return;
        }
        try {
            serviceLogin.addNewUser(newUser);
            newUser = null;
            otherUsers = null;
        } catch(Exception e) {
            FacesContext facesContext = FacesContext.getCurrentInstance();
            FacesMessage facesMessage = new FacesMessage( e.getMessage());
            facesContext.addMessage("GebruikerToevoegen:userID", facesMessage);
        }


    }

    public void cancleNewUser(){

        newUser = null;
    }

    public void oplaanEdit(){
        serviceLogin.updateUser(this.currentUser);

        this.currentUser = null;
    }


    private int wachtwoordControle(FacesContext facesContext){
        int errorCount = 0;

        if ((oldpassword == null || oldpassword.trim().length() == 0) &&
                (newPasswordA == null || newPasswordA.trim().length() == 0) &&
                (newPasswordB == null || newPasswordB.trim().length() == 0) ) {
            return 0;
        }

        if (oldpassword == null || oldpassword.trim().length() == 0) {
            FacesMessage fmActPassw = new FacesMessage( "Het Actuele wachtwoord is niet ingevuld.");
            facesContext.addMessage("updatePassword:ActueleWachtwoord", fmActPassw);
            errorCount++;
        }
        if (newPasswordA == null || newPasswordA.trim().length() == 0) {
            FacesMessage fmActPassw = new FacesMessage( "Het nieuwe wachtwoord is niet ingevuld.");
            facesContext.addMessage("updatePassword:NieuweWachtwoord", fmActPassw);
            errorCount++;
        }

        if (newPasswordB == null || newPasswordB.trim().length() == 0) {
            FacesMessage fmActPassw = new FacesMessage( "Controle nieuwe wachtwoord is niet ingevuld.");
            facesContext.addMessage("updatePassword:NieuweWachtwoordControle", fmActPassw);
            errorCount++;
        }

        if ((newPasswordA != null && newPasswordA.trim().length() > 0) &&
                (newPasswordB != null && newPasswordB.trim().length() > 0) ) {
            if(!newPasswordA.equals(newPasswordB)) {
                FacesMessage fmActPassw = new FacesMessage( "De nieuwe wachtwoorden zijn niet gelijk.");
                facesContext.addMessage("updatePassword:NieuweWachtwoordControle", fmActPassw);
                errorCount++;
            } else if (newPasswordA.equals(oldpassword)) {
                FacesMessage fmActPassw = new FacesMessage( "Het wachtwoord is niet gewijzigd.");
                facesContext.addMessage("updatePassword:WijzigWachtwoord", fmActPassw);
                errorCount++;
            }
        }

        if (newPasswordA.trim().length() < 8) {
            FacesMessage fmActPassw = new FacesMessage( "Het nieuwe wachtwoord moet minimaal 8 karakters bevatten.");
            facesContext.addMessage("updatePassword:NieuweWachtwoord", fmActPassw);
            facesContext.addMessage("updatePassword:NieuweWachtwoordControle", fmActPassw);
            errorCount++;
        }
        return errorCount;

    }

    public void updateMySelf(){
        FacesContext facesContext = FacesContext.getCurrentInstance();
        int errorCount = wachtwoordControle(facesContext);

        String oldVoornaam = getWebUserData().getVoornaam();
        String oldAchternaam = getWebUserData().getAchternaam();

        if (oldAchternaam.equals(alterUser.getAchternaam()) &&
                oldVoornaam.equals(alterUser.getVoornaam()) &&
                (oldpassword == null || oldpassword.trim().length() == 0 ) &&
                (newPasswordA == null || newPasswordA.trim().length() == 0 )) {
            FacesMessage fmActPassw = new FacesMessage( "Er zijn geen wijzigingen.");
            facesContext.addMessage("updatePassword:WijzigWachtwoord", fmActPassw);
            errorCount++;
        }

        if (errorCount > 0) {
            return;
        }

        if (!serviceLogin.wachtwoordNaInloggen(oldpassword, newPasswordA,alterUser)) {
            FacesMessage fmActPassw = new FacesMessage( "Het Actuele wachtwoord is niet correct.");
            facesContext.addMessage("updatePassword:ActueleWachtwoord", fmActPassw);
        } else {
            FacesMessage fmActPassw = new FacesMessage( "De wijzigingen zijn opgeslagen.");
            facesContext.addMessage("updatePassword:WijzigWachtwoord", fmActPassw);
        }
    }

    public void updateSignature(){
        if (newSignature != null) {
            try {
                byte[] dataImage = newSignature.getContent();
                String contentType = newSignature.getContentType();
                String filename = newSignature.getFileName();
                long size = newSignature.getSize();
                String extension = FilenameUtils.getExtension(filename);

                if (extension.equalsIgnoreCase("png")) {
                    String projectMap = reportingService.getBaseProjectMap();
                    Files.deleteIfExists(new File(projectMap, "signature.png").toPath());
                    Files.write(new File(projectMap, "signature.png").toPath(), dataImage);
                }
                newSignature = null;
            } catch (IOException e) {

            }
        }
    }

    public String getPngSignature(){
        return reportingService.getSignatureForLetter();
    }



    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public WebUserData getAlterUser() {
        return alterUser;
    }

    public void setAlterUser(WebUserData alterUser) {
        this.alterUser = alterUser;
    }

    public String getOldpassword() {
        return oldpassword;
    }

    public void setOldpassword(String oldpassword) {
        this.oldpassword = oldpassword;
    }

    public String getNewPasswordA() {
        return newPasswordA;
    }

    public void setNewPasswordA(String newPasswordA) {
        this.newPasswordA = newPasswordA;
    }

    public String getNewPasswordB() {
        return newPasswordB;
    }

    public void setNewPasswordB(String newPasswordB) {
        this.newPasswordB = newPasswordB;
    }

    public List<UserLevel> getAccessLevels() {
        return accessLevels;
    }

    public void setAccessLevels(List<UserLevel> accessLevels) {
        this.accessLevels = accessLevels;
    }

    public SearchUser getSearchUser() {
        return searchUser;
    }

    public void setSearchUser(SearchUser searchUser) {
        this.searchUser = searchUser;
    }

WebOfferAdmin/src/main/webapp/views/pdfDynamic/brief.xhtml
<!DOCTYPE html>
<html xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<head>
    <title>Jaaroverzicht</title>
</head>
<body>
    <ui:include src="header.xhtml" />
    <div style="display:block;overflow:hidden;padding-bottom:2cm;">
        <span>#{frontPageVisitorPdf.plaats} <h:outputText value="#{frontPageVisitorPdf.datum}"   >
                        <f:convertDateTime pattern="dd-MM-yyyy" timeZone="CET" type="date" />
                    </h:outputText></span><br />

        &#160;<br />
        &#160;<br />
        &#160;<br />
        &#160;<br />

        <span>#{frontPageVisitorPdf.aanhef} #{frontPageVisitorPdf.currentPayer.voornaam} #{frontPageVisitorPdf.currentPayer.achternaam}</span> <br />
        <span>#{frontPageVisitorPdf.currentPayer.straatnaam} #{frontPageVisitorPdf.currentPayer.nummer} #{frontPageVisitorPdf.currentPayer.toevoeging}</span> <br />
        <span>#{frontPageVisitorPdf.currentPayer.postcode} #{frontPageVisitorPdf.currentPayer.woonplaats}</span><br />
        &#160;<br />
        &#160;<br />
        &#160;<br />
        &#160;<br />
        &#160;<br />
        &#160;<br />
        &#160;<br />
        <p>
            Geachte #{frontPageVisitorPdf.aanroep} #{frontPageVisitorPdf.currentPayer.voornaam} #{frontPageVisitorPdf.currentPayer.achternaam},
            &#160;<br />
            &#160;<br />
            Hierbij bevestigen wij dat de Stichting Universele Kerk van Gods Rijk,
            gedurende #{frontPageVisitorPdf.jaartal}, een totaal giften bedrag <h:outputText value="#{frontPageVisitorPdf.jaarTotaal}" >
            <f:convertNumber type="currency"  locale="nl_NL" currencySymbol="€" />
        </h:outputText> van u heeft ontvangen, ten bate van werkzaamheden van de stichting.
        </p>
        &#160;<br />
        <p>
            Wij hopen u hiermee voldoende van dienst te zijn geweest. Wij danken u vriendelijk voor de giften.
            Indien u vragen heeft, kunt u contact opnemen met de hoofdvestiging op de kantoorlijn (070 388 84 42).
        </p>

        &#160;<br />
        &#160;<br />
        &#160;<br />
        &#160;<br />

        <img  src="#{frontPageVisitorPdf.pngSignature}" height="80px"/>

        &#160;<br />
        &#160;<br />

        <span>Namens de UKGR</span><br/>
        (Contactpersoon : #{director})

    </div>




</body>
</html>

WebOfferAdmin/src/main/webapp/views/pdfDynamic/header.xhtml
<ui:composition
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html">
    <table class="header">
        <tr>
            <td style="text-align: left;">#{title}</td>
        </tr>
    </table>

</ui:composition>

WebOfferAdmin/src/main/webapp/views/pdfDynamic/jaarData.xhtml
<ui:composition
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core">
    <div style="float:right;width: 4.1cm !important;margin-top:2cm;">
        <ui:repeat value="#{pdfReportBean.jaaroverzicht}" var="jaarItem">
            <div class="summary">
                <div class="labelu" >#{jaarItem.betaalmethode}</div>
                <div class="valueu" ><h:outputText value="#{jaarItem.totaal}" >
                    <f:convertNumber type="currency"  locale="nl_NL" currencySymbol="€" />
                </h:outputText></div>
            </div>
        </ui:repeat>
        <div class="summary hr" >
            <div class="labelu" ><strong>Totaal</strong></div>
            <div class="valueu" ><h:outputText value="#{pdfReportBean.jaarTotaal}" >
                <f:convertNumber type="currency"  locale="nl_NL" currencySymbol="€" />
            </h:outputText></div>
        </div>
    </div>
</ui:composition>

WebOfferAdmin/src/main/webapp/views/pdfDynamic/jaarDetailData.xhtml
<ui:composition
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core">
        <ui:repeat value="#{pdfReportBean.payerYearPageStart}" var="jaarItemStartPage">
            <div class="transacties">
                <div class="li">
                    <h:outputText value="#{jaarItemStartPage.transactiedatum}"   >
                        <f:convertDateTime pattern="dd-MM-yyyy" timeZone="CET" type="date" />
                    </h:outputText>
                </div>
                <div class="li method">#{jaarItemStartPage.betaalmethode}</div>
                <div class="li amount" style="text-align: right;">
                    <h:outputText value="#{jaarItemStartPage.bedrag}" >
                        <f:convertNumber type="currency"  locale="nl_NL" currencySymbol="€" />
                    </h:outputText>
                </div>
            </div>
        </ui:repeat>
</ui:composition>

WebOfferAdmin/src/main/webapp/views/pdfDynamic/jaarDetailDataEnd.xhtml
<ui:composition
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:repeat value="#{pdfReportBean.payerYearPageEnd}" var="jaarItemStartPage">
        <div class="transacties"  style="float:right !important;">
            <div class="li right amount" >
                <h:outputText value="#{jaarItemStartPage.bedrag}" >
                    <f:convertNumber type="currency"  locale="nl_NL" currencySymbol="€" />
                </h:outputText>
            </div>
            <div class="li right method"  >#{jaarItemStartPage.betaalmethode}</div>
            <div class="li right" >
                <h:outputText value="#{jaarItemStartPage.transactiedatum}"   >
                    <f:convertDateTime pattern="dd-MM-yyyy" timeZone="CET" type="date" />
                </h:outputText>
            </div>


        </div>
    </ui:repeat>

</ui:composition>

WebOfferAdmin/src/main/webapp/views/pdfDynamic/jaarlocatie.xhtml
<!DOCTYPE html>
<html  xmlns:ui="http://java.sun.com/jsf/facelets"
       xmlns:h="http://xmlns.jcp.org/jsf/html"
       xmlns:f="http://xmlns.jcp.org/jsf/core">
<head>
    <title>Jaaroverzicht per locatie</title>
</head>
<body>
    <h4 style="font-size: 18pt;color:red;margin-bottom: 0.5cm;">#{pdfLocatiesBean.locatiedata.woonplaats},
        #{pdfLocatiesBean.locatiedata.straatnaam}  [#{pdfLocatiesBean.jaartal}]</h4>
    <div style="display:block;overflow:hidden;">
        <table style="margin-bottom: 0;padding:0;" cellpadding="0" cellspacing="1">
            <tr>
                <td>&#160;  </td>
                <td>&#160;  </td>
                <td style="width:5.5cm !important;"><strong>Naam</strong></td>
                <td><strong>Postcode/Nr</strong></td>
            </tr>
            <ui:repeat value="#{pdfLocatiesBean.payerLeftData}" var="jaarPayer">
                <tr style="margin-bottom: 0px;">
                    <td style="width:20px;height:15px;border:1px solid darkgray;" >  </td>
                    <td>&#160;  </td>
                    <td> #{jaarPayer.voornaam} #{jaarPayer.achternaam}</td>
                    <td> #{jaarPayer.postcode}, #{jaarPayer.nummer}#{jaarPayer.toevoeging} (#{jaarPayer.straatnaam})</td>
                </tr>
            </ui:repeat>
        </table>
    </div>
</body>
</html>

WebOfferAdmin/src/main/webapp/views/pdfDynamic/page00.xhtml
<!DOCTYPE html>
<html xmlns:ui="http://java.sun.com/jsf/facelets">
<head>
    <title>Jaaroverzicht</title>
</head>
<body>
    <ui:include src="header.xhtml" />
    <div style="display:block;overflow:hidden;padding-bottom:2cm;">
        <div style="display: block;overflow:hidden;">
            <div style="float:left;width:7cm !important;">
                <ui:include src="persoonsinfo.xhtml" />
            </div>
            <div style="float:right;width:7cm !important;">
                <ui:include src="jaarData.xhtml" />
            </div>
        </div>
        <ui:fragment rendered="#{empty pdfReportBean.maandoverzicht}">
            <ui:include src="duoTable.xhtml" />
        </ui:fragment>
        <ui:fragment rendered="#{not empty pdfReportBean.maandoverzicht}">
            <ui:include src="taxOverzicht.xhtml" />
        </ui:fragment>
    </div>
</body>
</html>

WebOfferAdmin/src/main/webapp/views/pdfDynamic/pageJaarDuoTables.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets">
    <div style="display: inline-block;overflow:hidden;white-space: nowrap;">
        <div style="float:left;width:8cm !important;">
            <ui:fragment rendered="#{not empty pdfPayerLocatieYearBean.payerYearPageStart}">
                <ui:include src="pageJaarLeftData.xhtml" />
            </ui:fragment>
        </div>
        <div style="float:right;width:8cm !important;">
            <ui:fragment rendered="#{not empty pdfPayerLocatieYearBean.payerYearPageEnd}">
                <ui:include src="pageJaarRightData.xhtml" />
            </ui:fragment>
        </div>
    </div>
</ui:composition>

WebOfferAdmin/src/main/webapp/views/pdfDynamic/pageJaarLeftData.xhtml
<ui:composition
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core">
        <ui:repeat value="#{pdfPayerLocatieYearBean.payerYearPageStart}" var="jaarItemStartPage">
            <div class="transacties">
                <div class="li"><h:outputText value="#{jaarItemStartPage.postcode}"   /></div>
                <div class="li method">#{jaarItemStartPage.nummer}#{jaarItemStartPage.toevoeging}</div>
                <div class="li amount" style="text-align: right;">
                    <h:outputText value="#{jaarItemStartPage.ontvangen}" >
                        <f:convertNumber type="currency"  locale="nl_NL" currencySymbol="€" />
                    </h:outputText>
                </div>
            </div>
        </ui:repeat>
</ui:composition>

WebOfferAdmin/src/main/webapp/views/pdfDynamic/pageJaarLocatie.xhtml
<!DOCTYPE html>
<html xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<head>
    <title>Jaaroverzicht UKGR code #{pdfPayerLocatieYearBean.locatieUkgrCode}</title>
</head>
<body>
    <table class="header">
        <tr>
            <td style="text-align: left;">Jaaroverzicht #{pdfPayerLocatieYearBean.jaartal} UKGR#{pdfPayerLocatieYearBean.locatieUkgrCode} </td>
        </tr>
    </table>
    <div style="display:block;overflow:hidden;padding-bottom:2cm !important;">
        <div style="display: block;overflow:hidden;">
            <div style="float:left;width:7cm !important;">
                <div style="margin-top:2cm;">
                    <div class="naamdata">
                        <div  class="labelu" >Gemeente:</div>
                        <div class="valueu">#{pdfPayerLocatieYearBean.locatiePlaatsnaam}</div>
                    </div>
                    <div class="naamdata">
                        <div  class="labelu" >Postcode:</div>
                        <div class="valueu" >#{pdfPayerLocatieYearBean.locatiePostCode}</div>
                    </div>
                    <div  class="naamdata">
                        <div  class="labelu" >Adres:</div>
                        <div class="valueu" style="clear: both;"> #{pdfPayerLocatieYearBean.locatieStraatnaam} #{pdfPayerLocatieYearBean.locatieNummer}</div>
                    </div>
                    <div class="naamdata">
                        <div  class="labelu" >&#160;</div>
                        <div class="valueu" >&#160;</div>
                    </div>
                </div>
            </div>
            <div style="float:right;width:7cm !important;text-align: right;">
                <div style="float:right;width: 4.1cm !important;">
                    <div class="summary" >
                        <div class="labelu" ><strong>Totaal</strong></div>
                        <div class="valueu" ><h:outputText value="#{pdfPayerLocatieYearBean.locatieOntvangen}" >
                            <f:convertNumber type="currency"  locale="nl_NL" currencySymbol="€" />
                        </h:outputText></div>
                    </div>
                </div>
            </div>
        </div>
        <ui:fragment >
            <ui:include src="pageJaarDuoTables.xhtml" />
        </ui:fragment>
    </div>
</body>
</html>

WebOfferAdmin/src/main/webapp/views/pdfDynamic/pageJaarNamedData.xhtml
<ui:composition
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core">
        <ui:repeat value="#{pdfPayerLocatieYearFullDetailBean.payerYearPageStart}" var="jaarItemStartPage">
            <div class="transacties">
                <div class="li names">#{jaarItemStartPage.voornaam} #{jaarItemStartPage.achternaam}</div>
                <div class="li adres" > #{jaarItemStartPage.straatnaam}  #{jaarItemStartPage.nummer}#{jaarItemStartPage.toevoeging}, #{jaarItemStartPage.postcode} #{jaarItemStartPage.woonplaats}</div>
                <div class="li amount" style="text-align: right;">
                    <h:outputText value="#{jaarItemStartPage.ontvangen}" >
                        <f:convertNumber type="currency"  locale="nl_NL" currencySymbol="€" />
                    </h:outputText>
                </div>
            </div>
        </ui:repeat>
</ui:composition>

WebOfferAdmin/src/main/webapp/views/pdfDynamic/pageJaarNamedLocatie.xhtml
<!DOCTYPE html>
<html xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<head>
    <title>Jaaroverzicht UKGR code #{pdfPayerLocatieYearFullDetailBean.locatieUkgrCode}</title>
</head>
<body>
    <table class="header">
        <tr>
            <td style="text-align: left;">Jaaroverzicht #{pdfPayerLocatieYearFullDetailBean.jaartal} UKGR#{pdfPayerLocatieYearFullDetailBean.locatieUkgrCode} </td>
        </tr>
    </table>
    <div style="display:block;overflow:hidden;padding-bottom:2cm !important;">
        <div style="display: block;overflow:hidden;">
            <div style="float:left;width:7cm !important;">
                <div style="margin-top:2cm;">
                    <div class="naamdata">
                        <div  class="labelu" >Gemeente:</div>
                        <div class="valueu">#{pdfPayerLocatieYearFullDetailBean.locatiePlaatsnaam}</div>
                    </div>
                    <div class="naamdata">
                        <div  class="labelu" >Postcode:</div>
                        <div class="valueu" >#{pdfPayerLocatieYearFullDetailBean.locatiePostCode}</div>
                    </div>
                    <div  class="naamdata">
                        <div  class="labelu" >Adres:</div>
                        <div class="valueu" style="clear: both;"> #{pdfPayerLocatieYearFullDetailBean.locatieStraatnaam} #{pdfPayerLocatieYearFullDetailBean.locatieNummer}</div>
                    </div>
                    <div class="naamdata">
                        <div  class="labelu" >&#160;</div>
                        <div class="valueu" >&#160;</div>
                    </div>
                </div>
            </div>
            <div style="float:right;width:7cm !important;text-align: right;">
                <div style="float:right;width: 4.1cm !important;">
                    <div class="summary" >
                        <div class="labelu" ><strong>Totaal</strong></div>
                        <div class="valueu" ><h:outputText value="#{pdfPayerLocatieYearFullDetailBean.locatieOntvangen}" >
                            <f:convertNumber type="currency"  locale="nl_NL" currencySymbol="€" />
                        </h:outputText></div>
                    </div>
                </div>
            </div>
        </div>
        <ui:fragment >
            <ui:include src="pageJaarNamedData.xhtml" />
        </ui:fragment>
    </div>
</body>
</html>

WebOfferAdmin/src/main/webapp/views/pdfDynamic/pageJaarRightData.xhtml
<ui:composition
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:repeat value="#{pdfPayerLocatieYearBean.payerYearPageEnd}" var="jaarItemStartPage">
        <div class="transacties"  style="float:right !important;">
            <div class="li right amount" >
                <h:outputText value="#{jaarItemStartPage.ontvangen}" >
                    <f:convertNumber type="currency"  locale="nl_NL" currencySymbol="€" />
                </h:outputText>
            </div>
            <div class="li right method"  >#{jaarItemStartPage.nummer}#{jaarItemStartPage.toevoeging}</div>
            <div class="li right"><h:outputText value="#{jaarItemStartPage.postcode}"   /></div>
        </div>
    </ui:repeat>
</ui:composition>

WebOfferAdmin/src/main/webapp/views/pdfDynamic/persoonsinfo.xhtml
<ui:composition  xmlns:ui="http://java.sun.com/jsf/facelets">
    <div style="margin-top:2cm;">
        <div class="naamdata">
            <div class="labelu" >Naam:</div>
            <div class="valueu" style="clear: both;">#{pdfReportBean.currentPayer.voornaam} #{pdfReportBean.currentPayer.achternaam}</div>
        </div>
        <div  class="naamdata">
            <div  class="labelu" >Adres:</div>
            <div class="valueu" style="clear: both;"> #{pdfReportBean.currentPayer.straatnaam} #{pdfReportBean.currentPayer.nummer} #{pdfReportBean.currentPayer.toevoeging}</div>
        </div>
        <div class="naamdata">
            <div  class="labelu" >Woonplaats:</div>
            <div class="valueu">#{pdfReportBean.currentPayer.postcode} #{pdfReportBean.currentPayer.woonplaats}</div>
        </div>
        <div class="naamdata">
            <div  class="labelu" >Telefoon:</div>
            <div class="valueu" >#{pdfReportBean.currentPayer.telefoon}</div>
        </div>
        <div class="naamdata">
            <div  class="labelu" >&#160;</div>
            <div class="valueu" >&#160;</div>
        </div>
    </div>

</ui:composition>