WebOfferAdmin/src/main/java/com/crmweb/jsfbean/LetterBean.java
package com.crmweb.jsfbean;

import com.crmweb.services.MessageService;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.event.ValueChangeEvent;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;


@Slf4j
@ManagedBean
@ViewScoped
public class LetterBean extends BaseJsfBean {
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private transient MessageService messageService;
    private String briefData;
    private String editTag;

    private String currentTag;

    private Map<String, Path> tagToPathMap;

    @Override
    protected void initialize() {
        if (!isForAdmin()) {
            return;
        }

        if (Objects.isNull(currentTag)) {
            currentTag = "Bezoeker";
        }

        tagToPathMap = messageService.getTagToPathMap();

        this.setActiveMenuDef("Brieven");
        this.setViewTitle("Brief instellingen");
    }

    public String getBriefData() {
        return briefData;
    }

    public void setBriefData(String value) {

        this.briefData = value;
    }


    public String getEditTag() {
        return editTag;
    }

    public void exitEdit(boolean update) {
        if (update) {
            messageService.updateBrief(editTag, briefData);
        }
        editTag = null;
    }



    public void startChange() {
        if (currentTag != null) {
            log.info("current tag  =   {}", currentTag );
            briefData = messageService.fetchLetterData(currentTag);
            editTag = currentTag;
        }
    }

    public List<String> getTags() {
        return tagToPathMap.keySet().stream().collect(Collectors.toList());
    }

    public String getCurrentTag() {
        return currentTag;
    }

    public void setCurrentTag(String value) {
        this.currentTag = value;
    }


    public void changeTag(ValueChangeEvent e){
        String val = e.getNewValue().toString();

    }
}

WebOfferAdmin/src/main/webapp/views/brieven/edit.xhtml
<ui:composition
        xmlns:p="http://primefaces.org/ui"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html" >
        <h:form id="LetterEditorUpdater" name="LetterEditorUpdater"  >
            <h2>Wijzigen #{letterBean.currentTag}</h2>
            <p:defaultCommand target="saveMessageCmd" />
            <div style="display: block;overflow: hidden">
                <p:editor widgetVar="editorWidget"   id="boodschap" style="width:100%" process="@form"
                          value="#{letterBean.briefData}"     height="400"/>
                <div style="display: block;overflow: hidden">
                    <h:commandButton id="saveMessageCmd" styleClass="buttonSave"
                                     action="#{letterBean.exitEdit(true)}"  title="Opslaan" />

                    <h:commandButton id="cancleCmd" styleClass="buttonCancel"
                                     action="#{letterBean.exitEdit(false)}"  title="Annuleren" />

                </div>
            </div>
        </h:form>
</ui:composition>

WebOfferAdmin/src/main/webapp/views/brieven/index.xhtml
<ui:composition
        xmlns:p="http://primefaces.org/ui"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"

        template="../template/commonLayout.xhtml" >
    <ui:param name="usebean"  value="#{letterBean}"  />
    <ui:define name="content">
        <h:form id="selectEditItem" name="selectEditItem"
                rendered="#{empty letterBean.editTag }" >

            <h:selectOneListbox value="#{letterBean.currentTag}" >
                <f:selectItems value="#{letterBean.tags}" var="letterTag"
                               itemLabel="#{letterTag}" itemValue="#{letterTag}" />
                <f:ajax />
            </h:selectOneListbox>

            <h:commandButton  id="wijzigingen" styleClass="buttonEdit"
                              immediate="true"    action="#{letterBean.startChange}" />&#160;
        </h:form>

        <h:form id="editItem" name="editItem"
                rendered="#{not empty letterBean.editTag }" >
            <ui:include src="edit.xhtml" />
        </h:form>



    </ui:define>
</ui:composition>